### ISSUE TITLE
Add anchors to headings

### ISSUE THREAD

**Issue by arthur-shaw** [surveysolutions/docs#16]
Often, larger articles contain sub-sections to which one might want to provide a direct link. For example, I wanted to link to the "To copy and paste the categories from a document" heading [here](https://docs.mysurvey.solutions/questionnaire-designer/questions/categorical-single-select-question/).

@radyakin , does Hugo allow this?

For my main encounters with Markdown--RMarkdown and Quarto--there's an opinionated, batteries-included approach of making headings into anchors by default.

For Hugo, I found the following after some very cursory research:

- [Hugo forum](https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726?u=kaushalmodi)
- [Use render hooks](https://pavelkorolev.xyz/blog/2020-10-31-hugo-header-anchors/)
- [Use shortcodes/partials](https://www.jakewiesler.com/blog/anchored-headings-in-hugo)

**Comment by radyakin** [comment]
Possible, for example:
https://docs.mysurvey.solutions/questionnaire-designer/questions/gps-question#export
takes one directly to the `Export` section of the article.

**Comment by arthur-shaw** [comment]
Right. Belatedly, I noticed that one can construct a URL that points a heading.

But is there any way to make it such that one can click on a heading and get it's URL? 

For example, see [this site](https://pkgdown.r-lib.org/articles/pkgdown.html), an excerpt of which is reproduced below. When one hovers over a heading, an anchor symbol appears that indicates to the user that one can click on the heading to get the URL. Presumably, this involves some JavaScript library.

![image](https://github.com/surveysolutions/docs/assets/47256431/99937971-187a-4492-9585-8c7eb334c44b)
